owner: lasatagameplays
repo: Status-lasata.eu

sites:
  - name: Web Principal (LASATA)
    url: https://lasata.eu
  - name: Nube Privada (FileBrowser)
    url: https://archivos.lasata.eu
  - name: Webmail (HestiaCP)
    url: https://webmail.lasata.eu
  - name: Server S1 (HestiaCP)
    url: https://s1.lasata.eu:8083

status-website:
  cname: status.lasata.eu
  name: Status of lasata.eu 
  introTitle: "Monitorización Global de **LASATA.EU**"
  introMessage: "Bienvenido al centro de control. Supervisión en tiempo real de la infraestructura en la nube, servidores físicos y bases de datos. Actualizado cada 5 minutos."
  theme: dark
  publish: gh-pages
  # URL de tu logo (Puedes cambiar esta URL por la de cualquier imagen tuya)
  logoUrl: https://github.com/lasatagameplays/Status-lasata.eu/tree/master/assets/logo.png
  # Barra de navegación superior para que puedan volver a tu web
  navbar:
    - title: Volver a la Web Principal
      href: https://lasata.eu

i18n:
  activeIncidents: Incidentes Activos
  allSystemsOperational: Todos los sistemas operativos
  incidentReport: "Reporte de Incidente #$NUMBER"
  activeIncidentSummary: Abierto en $DATE con $POSTS publicaciones
  incidentTitle: Detalles del Incidente $NUMBER
  publishedAt: Publicado en $DATE
  unknown: Desconocido
  systems: Sistemas
  incidentHistory: Historial de Incidentes
  uptime: Tiempo de Actividad
  overallUptime: "Tiempo de actividad general: $UPTIME"
  yDay: "1 día"
  dDays: "$DAYS días"
  down: Caído
  up: Operativo
  degraded: Degradado
