owner: lasatagameplays
repo: status

sites:
  - name: Web Principal (LASATA)
    url: https://lasata.eu
  - name: Nube Privada (FileBrowser)
    url: https://archivos.lasata.eu
  - name: Webmail (HestiaCP)
    url: https://webmail.lasata.eu
  - name: Server S1 (HestiaCP)
    url: https://s1.lasata.eu

status-website:
  cname: status.lasata.eu
  name: LASATA System Status
  introTitle: "**LASATA** Monitorización Global"
  introMessage: Bienvenido a la página oficial de estado. Aquí puedes comprobar en tiempo real la disponibilidad de todos nuestros servidores y servicios en la nube.
  theme: dark
  publish: gh-pages

i18n:
  activeIncidents: Incidentes Activos
  allSystemsOperational: Todos los sistemas operativos
  incidentReport: "Reporte de Incidente #$NUMBER"
  activeIncidentSummary: Abierto en $DATE con $POSTS publicaciones
  incidentTitle: Detalles del Incidente $NUMBER
  publishedAt: Publicado en $DATE
  unknown: Desconocido
  systems: Sistemas
  incidentHistory: Historial de Incidentes
  uptime: Tiempo de Actividad
  overallUptime: "Tiempo de actividad general: $UPTIME"
  yDay: "1 día"
  dDays: "$DAYS días"
  down: Caído
  up: Operativo
  degraded: Degradado
